image: node:10

stages:
  - lint
  - build
  - publish

before_script:
  - echo $NPMJS_AUTH_TOKEN > .npmrc
  - npm ci

Check Sourcecode:
  stage: lint
  script:
    - npm run lint
    - npm run build
    - npm run test

Build Package:
  stage: build
  script:
    - npm run build

Publish Package:
  stage: publish
  only: ['tags']
  script:
    - npm run build
    - npm publish --access public
